# Generated by Django 5.0.2 on 2024-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('subtotal_detalle_pedido', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_pedido', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('estrellas_pedido', models.IntegerField(blank=True, null=True)),
                ('comentario_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
    ]
