# Generated by Django 5.0.2 on 2024-02-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria',
            new_name='id_categoria_fk',
        ),
    ]
