# Generated by Django 5.0.2 on 2024-02-16 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('producto', '0002_rename_id_categoria_producto_id_categoria_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_categoria_fk',
            field=models.ForeignKey(db_column='id_categoria_fk', on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
    ]
