# Generated by Django 5.0.2 on 2024-02-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0002_remove_ordencompra_id_estado_oc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
