# Generated by Django 5.0.2 on 2024-02-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('celular_proveedor', models.CharField(max_length=20)),
                ('correo_proveedor', models.EmailField(max_length=255)),
                ('celular_respaldo_proveedor', models.CharField(max_length=20)),
                ('empresa_proveedor', models.CharField(max_length=255)),
                ('estado_proveedor', models.BooleanField(default=True)),
                ('nit_proveedor', models.CharField(max_length=20)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
    ]
