# Generated by Django 5.0.2 on 2024-02-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
    ]
