# Generated by Django 5.0.2 on 2024-02-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
    ]
