# Generated by Django 5.0.2 on 2024-02-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_pedido', models.DateField()),
                ('id_estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado_pedido.estadopedido')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
