# Generated by Django 5.0.2 on 2024-02-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='descripcion',
            new_name='descripcion_pedido',
        ),
    ]
