# Generated by Django 5.0.2 on 2024-02-16 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_pedido', '0001_initial'),
        ('pedido', '0002_rename_descripcion_pedido_descripcion_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_estado_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_estado_pedido_fk',
            field=models.ForeignKey(blank=True, db_column='id_estado_pedido_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_pedido.estadopedido'),
        ),
    ]
