# Generated by Django 5.0.2 on 2024-02-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_no_documento_usuario_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
