# Generated by Django 5.0.2 on 2024-02-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='calificacion_pedido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
