# Generated by Django 5.0.2 on 2024-02-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('comentario_calificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estrallas_calificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOc',
            fields=[
                ('id_detalle_oc', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_insumo', models.IntegerField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'detalle_oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('subtotal_detalle_pedido', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('subtotal_detalle_venta', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoInsumo',
            fields=[
                ('id_estado_insumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_estado_insumo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'estado_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOc',
            fields=[
                ('id_estado_oc', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_estado_oc', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'estado_oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_historico', models.IntegerField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('tipo_historico', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_inventario', models.IntegerField(blank=True, null=True)),
                ('tipo_inventario', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OcHasProveedor',
            fields=[
                ('id_oc_has_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'oc_has_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_oc', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_oc', models.DateField(blank=True, null=True)),
                ('hora_oc', models.TimeField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_pedido', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_permiso', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_producto', models.IntegerField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('celular_proveedor', models.BigIntegerField(blank=True, null=True)),
                ('celular_respaldo_proveedor', models.BigIntegerField(blank=True, null=True)),
                ('correo_proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa_proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_proveedor', models.TextField(blank=True, null=True)),
                ('nit_proveedor', models.BigIntegerField(blank=True, null=True)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolHasPermiso',
            fields=[
                ('id_rol_has_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'rol_has_permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id_sabor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_sabor', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'sabor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaborHasProducto',
            fields=[
                ('id_sabor_has_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'sabor_has_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id_tipo_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_movimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'tipo_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('no_documento_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellido_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('celular_usuario', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('hora_venta', models.TimeField(blank=True, null=True)),
                ('total_venta', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
