# Generated by Django 5.0.2 on 2024-02-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('sabor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaborHasProducto',
            fields=[
                ('id_sabor_has_producto', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('id_sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabor.sabor')),
            ],
            options={
                'db_table': 'sabor_has_producto',
            },
        ),
    ]
