# Generated by Django 5.0.2 on 2024-02-16 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_id_categoria_fk'),
        ('sabor', '0001_initial'),
        ('sabor_has_producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saborhasproducto',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='saborhasproducto',
            name='id_sabor',
        ),
        migrations.AddField(
            model_name='saborhasproducto',
            name='id_producto_fk',
            field=models.ForeignKey(blank=True, db_column='id_producto_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
        migrations.AddField(
            model_name='saborhasproducto',
            name='id_sabor_fk',
            field=models.ForeignKey(blank=True, db_column='id_sabor_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='sabor.sabor'),
        ),
    ]
