# Generated by Django 5.0.2 on 2024-02-16 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_venta', '0001_initial'),
        ('producto', '0003_alter_producto_id_categoria_fk'),
        ('venta', '0002_remove_venta_id_pedido_venta_id_pedido_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_producto_fk',
            field=models.ForeignKey(blank=True, db_column='id_producto_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_venta_fk',
            field=models.ForeignKey(blank=True, db_column='id_venta_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
        ),
    ]
