# Generated by Django 5.0.2 on 2024-02-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_remove_historico_id_insumo_and_more'),
        ('tipo_movimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='id_tipo_movimiento',
        ),
        migrations.AddField(
            model_name='historico',
            name='id_tipo_movimiento_fk',
            field=models.ForeignKey(blank=True, db_column='id_tipo_movimiento_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_movimiento.tipomovimiento'),
        ),
    ]
