# Generated by Django 5.0.2 on 2024-02-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_remove_historico_id_tipo_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
