# Generated by Django 5.0.2 on 2024-02-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden_compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCHasProveedor',
            fields=[
                ('id_has_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('id_oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompra')),
            ],
            options={
                'db_table': 'oc_has_proveedor',
            },
        ),
    ]
