# Generated by Django 5.0.2 on 2024-02-16 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_has_provedor', '0001_initial'),
        ('orden_compra', '0003_ordencompra_estado'),
        ('proveedor', '0004_alter_proveedor_celular_respaldo_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ochasproveedor',
            name='id_oc',
        ),
        migrations.AddField(
            model_name='ochasproveedor',
            name='id_oc_fk',
            field=models.ForeignKey(blank=True, db_column='id_oc_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompra'),
        ),
        migrations.AddField(
            model_name='ochasproveedor',
            name='id_proveedor_fk',
            field=models.ForeignKey(blank=True, db_column='id_proveedor_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
