# Generated by Django 5.0.2 on 2024-02-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permiso', '0001_initial'),
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolHasPermiso',
            fields=[
                ('id_rol_has_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permiso.permiso')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
            options={
                'db_table': 'rol_has_permiso',
            },
        ),
    ]
