# Generated by Django 5.0.2 on 2024-02-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol_has_permisos', '0002_remove_rolhaspermiso_id_permiso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolhaspermiso',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
