# Generated by Django 5.0.2 on 2024-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_permiso', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolHasPermiso',
            fields=[
                ('id_rol_has_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'rol_has_permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('no_documento_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellido_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('celular_usuario', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
