# Generated by Django 5.0.2 on 2024-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoInsumo',
            fields=[
                ('id_estado_insumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_estado_insumo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'estado_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_historico', models.IntegerField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('tipo_historico', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_inventario', models.IntegerField(blank=True, null=True)),
                ('tipo_inventario', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_producto', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id_sabor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_sabor', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'sabor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaborHasProducto',
            fields=[
                ('id_sabor_has_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'sabor_has_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id_tipo_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_movimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'tipo_movimiento',
                'managed': False,
            },
        ),
    ]
