# Generated by Django 5.0.2 on 2024-02-16 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_estado'),
        ('venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='venta',
            name='id_pedido_fk',
            field=models.ForeignKey(blank=True, db_column='id_pedido_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='no_documento_usuario_fk',
            field=models.ForeignKey(blank=True, db_column='no_documento_usuario_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
