# Generated by Django 5.0.2 on 2024-02-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_oc', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOC',
            fields=[
                ('id_detalle_oc', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_insumo', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
                ('id_oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado_oc.estadooc')),
            ],
            options={
                'db_table': 'detalle_oc',
            },
        ),
    ]
