# Generated by Django 5.0.2 on 2024-02-16 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_oc', '0001_initial'),
        ('estado_oc', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleoc',
            name='id_insumo',
        ),
        migrations.RemoveField(
            model_name='detalleoc',
            name='id_oc',
        ),
        migrations.AddField(
            model_name='detalleoc',
            name='id_insumo_fk',
            field=models.ForeignKey(blank=True, db_column='id_insumo_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo'),
        ),
        migrations.AddField(
            model_name='detalleoc',
            name='id_oc_fk',
            field=models.ForeignKey(blank=True, db_column='id_oc_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_oc.estadooc'),
        ),
    ]
