# Generated by Django 5.0.2 on 2024-02-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_oc', '0002_remove_detalleoc_id_insumo_remove_detalleoc_id_oc_and_more'),
        ('orden_compra', '0003_ordencompra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleoc',
            name='id_oc_fk',
            field=models.ForeignKey(blank=True, db_column='id_oc_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompra'),
        ),
    ]
