# Generated by Django 5.0.2 on 2024-02-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
        ('usuarios', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rol.rol'),
        ),
    ]
