# Generated by Django 5.0.2 on 2024-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('subtotal_detalle_venta', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('hora_venta', models.TimeField(blank=True, null=True)),
                ('total_venta', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
