# Generated by Django 5.0.2 on 2024-02-16 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
        ('proveedor', '0004_alter_proveedor_celular_respaldo_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_proveedor_fk',
            field=models.ForeignKey(blank=True, db_column='id_proveedor_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
