# Generated by Django 5.0.2 on 2024-02-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=255)),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
