# Generated by Django 5.0.2 on 2024-02-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso',
            old_name='description_permiso',
            new_name='descripcion_permiso',
        ),
    ]
